/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.syslib;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author engenheiro
 */
public class NewFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewFrame
     */
    public NewFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        loginScreen = new javax.swing.JPanel();
        name1 = new javax.swing.JLabel();
        contentArea = new javax.swing.JPanel();
        loginContent = new javax.swing.JPanel();
        passwordTextField = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        buttonEsqueciSenha = new javax.swing.JLabel();
        buttonSouBibliotecario = new javax.swing.JLabel();
        catalogoScreen = new javax.swing.JPanel();
        name2 = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        contentArea1 = new javax.swing.JPanel();
        booksLabel = new javax.swing.JLabel();
        myBooksLabel = new javax.swing.JLabel();
        recentBooksLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setLayout(new java.awt.CardLayout());

        loginScreen.setBackground(new java.awt.Color(243, 243, 243));

        name1.setBackground(new java.awt.Color(62, 67, 159));
        name1.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name1.setText("Syslib");
        name1.setToolTipText("");
        name1.setOpaque(true);

        loginContent.setBackground(new java.awt.Color(217, 217, 217));
        loginContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Faça seu login para continuar");
        title.setToolTipText("");

        emailTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        loginButton.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        loginButton.setLabel("Entrar");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        buttonEsqueciSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonEsqueciSenha.setText("Esqueci a senha");

        buttonSouBibliotecario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonSouBibliotecario.setText("Sou bibliotecário(a)");

        javax.swing.GroupLayout loginContentLayout = new javax.swing.GroupLayout(loginContent);
        loginContent.setLayout(loginContentLayout);
        loginContentLayout.setHorizontalGroup(
            loginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonEsqueciSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginContentLayout.createSequentialGroup()
                .addGroup(loginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginContentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonSouBibliotecario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(loginContentLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(loginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 90, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginContentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );
        loginContentLayout.setVerticalGroup(
            loginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContentLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(title)
                .addGap(29, 29, 29)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonEsqueciSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSouBibliotecario)
                .addContainerGap())
        );

        javax.swing.GroupLayout contentAreaLayout = new javax.swing.GroupLayout(contentArea);
        contentArea.setLayout(contentAreaLayout);
        contentAreaLayout.setHorizontalGroup(
            contentAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentAreaLayout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(loginContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );
        contentAreaLayout.setVerticalGroup(
            contentAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentAreaLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(loginContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginScreenLayout = new javax.swing.GroupLayout(loginScreen);
        loginScreen.setLayout(loginScreenLayout);
        loginScreenLayout.setHorizontalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginScreenLayout.setVerticalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginScreenLayout.createSequentialGroup()
                .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        backgroundPanel.add(loginScreen, "card3");

        catalogoScreen.setBackground(new java.awt.Color(243, 243, 243));

        name2.setBackground(new java.awt.Color(62, 67, 159));
        name2.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        name2.setForeground(new java.awt.Color(255, 255, 255));
        name2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name2.setText("Syslib");
        name2.setToolTipText("");
        name2.setOpaque(true);

        contentArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));

        booksLabel.setText("Livros");

        myBooksLabel.setText("Meus Livros");

        recentBooksLabel.setText("Livros recentes");

        javax.swing.GroupLayout contentArea1Layout = new javax.swing.GroupLayout(contentArea1);
        contentArea1.setLayout(contentArea1Layout);
        contentArea1Layout.setHorizontalGroup(
            contentArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentArea1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myBooksLabel)
                    .addComponent(recentBooksLabel)
                    .addComponent(booksLabel))
                .addContainerGap(907, Short.MAX_VALUE))
        );
        contentArea1Layout.setVerticalGroup(
            contentArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentArea1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(myBooksLabel)
                .addGap(237, 237, 237)
                .addComponent(recentBooksLabel)
                .addGap(252, 252, 252)
                .addComponent(booksLabel)
                .addContainerGap(671, Short.MAX_VALUE))
        );

        ScrollPane.setViewportView(contentArea1);

        javax.swing.GroupLayout catalogoScreenLayout = new javax.swing.GroupLayout(catalogoScreen);
        catalogoScreen.setLayout(catalogoScreenLayout);
        catalogoScreenLayout.setHorizontalGroup(
            catalogoScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addGroup(catalogoScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane)
                .addContainerGap())
        );
        catalogoScreenLayout.setVerticalGroup(
            catalogoScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catalogoScreenLayout.createSequentialGroup()
                .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        backgroundPanel.add(catalogoScreen, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        loginScreen.setVisible(false);
        catalogoScreen.setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel booksLabel;
    private javax.swing.JLabel buttonEsqueciSenha;
    private javax.swing.JLabel buttonSouBibliotecario;
    private javax.swing.JPanel catalogoScreen;
    private javax.swing.JPanel contentArea;
    private javax.swing.JPanel contentArea1;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginContent;
    private javax.swing.JPanel loginScreen;
    private javax.swing.JLabel myBooksLabel;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel recentBooksLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    public JScrollPane getScrollPane() {
        return ScrollPane;
    }

    public void setScrollPane(JScrollPane ScrollPane) {
        this.ScrollPane = ScrollPane;
    }

    public JPanel getBackgroundPanel() {
        return backgroundPanel;
    }

    public void setBackgroundPanel(JPanel backgroundPanel) {
        this.backgroundPanel = backgroundPanel;
    }

    public JLabel getBooksLabel() {
        return booksLabel;
    }

    public void setBooksLabel(JLabel booksLabel) {
        this.booksLabel = booksLabel;
    }

    public JLabel getButtonEsqueciSenha() {
        return buttonEsqueciSenha;
    }

    public void setButtonEsqueciSenha(JLabel buttonEsqueciSenha) {
        this.buttonEsqueciSenha = buttonEsqueciSenha;
    }

    public JLabel getButtonSouBibliotecario() {
        return buttonSouBibliotecario;
    }

    public void setButtonSouBibliotecario(JLabel buttonSouBibliotecario) {
        this.buttonSouBibliotecario = buttonSouBibliotecario;
    }

    public JPanel getCatalogoScreen() {
        return catalogoScreen;
    }

    public void setCatalogoScreen(JPanel catalogoScreen) {
        this.catalogoScreen = catalogoScreen;
    }

    public JPanel getContentArea() {
        return contentArea;
    }

    public void setContentArea(JPanel contentArea) {
        this.contentArea = contentArea;
    }

    public JPanel getContentArea1() {
        return contentArea1;
    }

    public void setContentArea1(JPanel contentArea1) {
        this.contentArea1 = contentArea1;
    }

    public JTextField getEmailTextField() {
        return emailTextField;
    }

    public void setEmailTextField(JTextField emailTextField) {
        this.emailTextField = emailTextField;
    }

    public JButton getLoginButton() {
        return loginButton;
    }

    public void setLoginButton(JButton loginButton) {
        this.loginButton = loginButton;
    }

    public JPanel getLoginContent() {
        return loginContent;
    }

    public void setLoginContent(JPanel loginContent) {
        this.loginContent = loginContent;
    }

    public JPanel getLoginScreen() {
        return loginScreen;
    }

    public void setLoginScreen(JPanel loginScreen) {
        this.loginScreen = loginScreen;
    }

    public JLabel getMyBooksLabel() {
        return myBooksLabel;
    }

    public void setMyBooksLabel(JLabel myBooksLabel) {
        this.myBooksLabel = myBooksLabel;
    }

    public JLabel getName1() {
        return name1;
    }

    public void setName1(JLabel name1) {
        this.name1 = name1;
    }

    public JLabel getName2() {
        return name2;
    }

    public void setName2(JLabel name2) {
        this.name2 = name2;
    }

    public JTextField getPasswordTextField() {
        return passwordTextField;
    }

    public void setPasswordTextField(JTextField passwordTextField) {
        this.passwordTextField = passwordTextField;
    }

    public JLabel getRecentBooksLabel() {
        return recentBooksLabel;
    }

    public void setRecentBooksLabel(JLabel recentBooksLabel) {
        this.recentBooksLabel = recentBooksLabel;
    }
}
